[package]
name = "stackable_config"
version = "0.1.0-nightly"
authors = ["Lars Francke <lars.francke@stackable.de>"]
edition = "2018"
license = "Apache-2.0"
description = "Library to help with CLI argument parsing and definition"

[dependencies]
bstr = "0.2"
clap = "2"
anyhow = "1"
