[package]
authors = ["Lars Francke <lars.francke@stackable.de>"]
description = "Library to help with CLI argument parsing and definition"
edition = "2018"
license = "Apache-2.0"
name = "stackable-config"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
bstr = "0.2"
clap = "2.33"
log = "0.4"
